name: Print Event
on:
  pull_request:
    types: [opened, closed, reopened]
  issue_comment:
    types: [created]
jobs:
  printEvent:
    name: Print Event Payload
    runs-on: ubuntu-latest
    steps:
      - name: Dump context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"